# -*- coding: utf-8 -*-
"""single youtube video downloader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMMuoss9igZqi6QQcjQocupLAfa08wxa

## YouTube Video Downloader

First, we need to install the `yt-dlp` library, which is a command-line program to download videos from YouTube and other video sites. We'll use `pip` to install it.
"""

pip install yt-dlp

print('Installing nodejs for yt-dlp JavaScript runtime support...')
!sudo apt-get update && sudo apt-get install -y nodejs
print('nodejs installation complete.')

"""Now, let's define a function that takes a YouTube video URL and downloads it as an MP4 file. We'll use the `subprocess` module to run `yt-dlp` from Python."""

import subprocess
import os

def download_youtube_video_as_mp4(youtube_url, output_filename=None):
    """
    Downloads a YouTube video as an MP4 file.

    Args:
        youtube_url (str): The URL of the YouTube video.
        output_filename (str, optional): The desired output filename (e.g., 'my_video.mp4').
                                         If None, yt-dlp will generate a filename.
    """
    print(f"Attempting to download video from: {youtube_url}")

    # Construct the yt-dlp command
    # -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' tries to get an MP4 version
    # --recode-video mp4 ensures the final output is MP4
    # -o specifies the output template. If output_filename is provided, it uses that.
    #    Otherwise, yt-dlp's default output template is used.

    command = [
        'yt-dlp',
        '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        '--recode-video', 'mp4'
    ]

    if output_filename:
        # Ensure the filename ends with .mp4 if not already
        if not output_filename.lower().endswith('.mp4'):
            output_filename += '.mp4'
        command.extend(['-o', output_filename])

    command.append(youtube_url)

    try:
        # Run the command
        process = subprocess.run(command, capture_output=True, text=True, check=True)
        print("Download complete!")
        print("Output:\n", process.stdout)
        if process.stderr:
            print("Errors/Warnings:\n", process.stderr)
        if output_filename:
            print(f"Video saved as: {output_filename}")
        else:
            # Try to infer the downloaded filename if not specified
            # This is a heuristic and might not always work perfectly
            if "Destination:" in process.stdout:
                start = process.stdout.find("Destination:") + len("Destination:")
                end = process.stdout.find("\n", start)
                detected_filename = process.stdout[start:end].strip()
                print(f"Video likely saved as: {detected_filename}")
            else:
                print("Could not automatically detect output filename. Check the output above.")

    except subprocess.CalledProcessError as e:
        print(f"An error occurred during download:\n{e.stderr}")
    except FileNotFoundError:
        print("Error: yt-dlp not found. Make sure it's installed and in your system's PATH.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

"""Finally, let's demonstrate how to use this function. Replace `YOUR_YOUTUBE_VIDEO_URL` with the actual URL of the video you want to download. You can also specify an `output_filename`."""

# Example Usage:
# Replace with the URL of the YouTube video you want to download
youtube_link = 'https://www.youtube.com/shorts/uMFhVF0XoPA'

# Call the function to download the video
# You can optionally provide a filename, e.g., 'Rick_Astley.mp4'
download_youtube_video_as_mp4(youtube_link, output_filename='my_youtube_video.mp4')

# After running, the video file (e.g., 'my_youtube_video.mp4') should appear in your Colab files panel.